export const ESTADO_RADICADO = {
  1: "En revisión",
  2: "Inactivo/Rechazado",
  3: "Inactivo/Rechazado"
};

export const TIPO_SOLICITUD = {
  1: "DERECHOS DE PETICIÓN",
  2: "SOLICITUD DE COPIAS",
  3: "CONSULTAS",
  4: "PODERES",
  5: "RECURSOS",
  6: "TRASLADOS",
  7: "ARGUMENTOS DE DEFENSA",
  8: "VERSIONES LIBRE",
  9: "SOLICITUD DE PRUEBAS",
  10: "PRUEBAS RECIBIDAS",
  11: "NULIDADES",
  12: "INFORMES TÉCNICOS",
  13: "HALLAZGOS",
  14: "RESPUESTAS CIRCULARIZACIÓN -EMBARGOS",
  15: "RESPUESTAS A PETICIONES",
  16: "COMUNICACIONES ESTADO",
  17: "COMUNICACIONES PERSONALES",
  18: "CITACIONES",
  19: "AVISOS",
  20: "NOTAS SECRETARIALES ESTADO",
  21: "NOTAS SECRETARIALES PERSONAL",
  22: "REMISIONES SEGUNDA INSTANCIA",
  23: "SOLICITUD DE INFORMACIÓN",
  24: "TRASLADO A COACTIVA",
  25: "PUBLICACIÓN DE ESTADO"
};
